# Generated by Django 4.2.5 on 2023-10-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userSignUp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_db",
            old_name="token",
            new_name="tokens",
        ),
    ]
