# Generated by Django 4.2.5 on 2023-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userSignUp", "0002_rename_token_user_db_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_db",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
