# Generated by Django 4.2.5 on 2023-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userSignUp", "0003_alter_user_db_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="admin_add_auction_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=256)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("start_price", models.IntegerField()),
            ],
        ),
    ]
