# Generated by Django 4.2.5 on 2023-10-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("userSignUp", "0004_admin_add_auction_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_amount", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "auction_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userSignUp.admin_add_auction_items",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userSignUp.user_db",
                    ),
                ),
            ],
        ),
    ]
